Repository janosh/pymatviz, pull requests merged in 2024-11, with the labels that each got.

#238 Speedup import and add regression check for import time
  .pre-commit-config.yaml
  pymatviz/__init__.py
  pymatviz/coordination.py
  pymatviz/process_data.py
  pymatviz/ptable/ptable_plotly.py
  pymatviz/structure_viz/helpers.py
  pymatviz/structure_viz/mpl.py
  pymatviz/structure_viz/plotly.py
  pymatviz/utils.py
  pyproject.toml
  tests/performance_tests/test_import_time.py
  tests/test_coordination.py
Labels: ux, pkg

#226 Fix `ptable_heatmap_ratio` following change of default `count_elements` `fill_value` to 0
  examples/dataset_exploration/boltztrap_mp/boltztrap_mp-ptable-heatmap.pdf
  examples/mp_bimodal_e_form.ipynb
  examples/mprester_ptable.ipynb
  pymatviz/histogram.py
  pymatviz/process_data.py
  pymatviz/ptable/ptable_matplotlib.py
  pymatviz/ptable/ptable_plotly.py
  tests/ptable/test_ptable_matplotlib.py
  tests/test_process_data.py
Labels: breaking, api

#239 Split `coordination.py` module into `plotly.py` and `helpers.py`
  .pre-commit-config.yaml
  examples/make_assets/coordination.py
  pymatviz/coordination/__init__.py
  pymatviz/coordination/helpers.py
  pymatviz/coordination/plotly.py
  pymatviz/enums.py
  pymatviz/utils.py
  readme.md
  tests/coordination/test_helpers.py
  tests/coordination/test_plotly.py
Labels: testing, housekeeping

#240 Enhance warning message for default return type change of `ptable_heatmap`
  examples/make_assets/ptable/ptable_matplotlib.py
  pymatviz/ptable/ptable_matplotlib.py
  tests/ptable/test_ptable_matplotlib.py
Labels: matplotlib, api, ptable

#244 Better `ptable_hists_plotly` defaults
  assets/ptable-hists-plotly.svg
  examples/dataset_exploration/matpes/eda.py
  examples/make_assets/ptable/ptable_matplotlib.py
  examples/make_assets/ptable/ptable_plotly.py
  pymatviz/ptable/ptable_matplotlib.py
  pymatviz/ptable/ptable_plotly.py
  pymatviz/utils.py
  tests/ptable/test_ptable_plotly.py
Labels: enhancement, plotly, ptable, histograms

#249 `phonon_bands` enable custom acoustic/optical bands
  assets/scripts/phonons/phonon_bands.py
  pymatviz/phonons.py
  pymatviz/ptable/ptable_plotly.py
  tests/test_phonons.py
Labels: enhancement, phonons

#248 [Breaking] Split `utils` into sub-modules, move `typing` from `utils` to root (`pmv.typing`)
  assets/scripts/coordination/coordination_hist.py
  assets/scripts/coordination/coordination_vs_cutoff_line.py
  assets/scripts/histogram/spacegroup_bar.py
  assets/scripts/phonons/phonon_bands.py
  assets/scripts/phonons/phonon_bands_and_dos.py
  assets/scripts/phonons/phonon_dos.py
  assets/scripts/structure_viz/structure_2d.py
  assets/scripts/xrd/xrd_pattern.py
  pymatviz/__init__.py
  pymatviz/bar.py
  pymatviz/histogram.py
  pymatviz/powerups/both.py
  pymatviz/process_data.py
  pymatviz/ptable/ptable_matplotlib.py
  pymatviz/ptable/ptable_plotly.py
  pymatviz/typing.py
  pymatviz/utils.py
  pymatviz/utils/__init__.py
  pymatviz/utils/data.py
  pymatviz/utils/plotting.py
  pymatviz/utils/testing.py
  readme.md
  tests/performance_tests/test_import_time.py
  tests/powerups/test_both_powerups.py
  tests/ptable/test_ptable_plotly.py
  tests/test_bar.py
  tests/test_histogram.py
  tests/test_phonons.py
  tests/test_xrd.py
  tests/utils/test_data.py
  tests/utils/test_init.py
  tests/utils/test_plotting.py
Labels: breaking, ux, api, dx

#252 Add `pymatviz.classify.confusion_matrix`
  assets/scripts/classify/confusion_matrix.py
  assets/svg/crystal-system-confusion-matrix.svg
  assets/svg/stability-confusion-matrix.svg
  pymatviz/__init__.py
  pymatviz/classify/__init__.py
  pymatviz/classify/confusion_matrix.py
  readme.md
  tests/classify/test_confusion_matrix.py
Labels: plotly, feature, classification

#253 `plotly` ROC and precision-recall curves
  assets/scripts/classify/precision_recall_curve.py
  assets/scripts/classify/roc_curve.py
  assets/scripts/relevance/precision_recall_curve.py
  assets/scripts/relevance/roc_curve.py
  assets/svg/precision-recall-curve-plotly-multiple.svg
  assets/svg/roc-curve-plotly-multiple.svg
  assets/svg/roc-curve.svg
  pymatviz/__init__.py
  pymatviz/classify/__init__.py
  pymatviz/classify/curves_matplotlib.py
  pymatviz/classify/curves_plotly.py
  readme.md
  tests/classify/test_curves_matplotlib.py
  tests/classify/test_curves_plotly.py
Labels: enhancement, plotly, breaking, classification

#254 Delete `pymatviz/classify/curves_matplotlib.py`
  assets/scripts/classify/precision_recall_curve.py
  assets/scripts/classify/roc_curve.py
  assets/svg/precision-recall-curve.svg
  assets/svg/roc-curve.svg
  pymatviz/__init__.py
  pymatviz/classify/__init__.py
  pymatviz/classify/curves.py
  pymatviz/classify/curves_matplotlib.py
  readme.md
  tests/.pytest-split-durations
  tests/classify/test_curves.py
  tests/classify/test_curves_matplotlib.py
Labels: housekeeping, breaking

#255 Add element color schemes `alloys`
  assets/scripts/ptable_plotly/ptable_heatmap_splits_plotly.py
  assets/svg/ptable-heatmap-splits-plotly-2-color-schemes.svg
  assets/svg/ptable-heatmap-splits-plotly-3-color-schemes.svg
  pymatviz/colors.py
  pymatviz/coordination/plotly.py
  pymatviz/enums.py
  pymatviz/ptable/ptable_plotly.py
  pymatviz/structure_viz/helpers.py
  pymatviz/structure_viz/mpl.py
  pymatviz/structure_viz/plotly.py
  pymatviz/typing.py
  tests/coordination/test_plotly.py
  tests/performance_tests/test_import_time.py
  tests/ptable/test_ptable_plotly.py
  tests/structure_viz/test_structure_viz_helpers.py
  tests/structure_viz/test_structure_viz_mpl.py
  tests/test_colors.py
Labels: enhancement, plotly, colors

#251 Add `brillouin_zone_3d` plot function
  .github/workflows/test.yml
  assets/scripts/brillouin/brillouin_zone_3d.py
  assets/svg/brillouin-cubic-mp-10018.svg
  assets/svg/brillouin-hexagonal-mp-862690.svg
  assets/svg/brillouin-monoclinic-mp-1183089.svg
  assets/svg/brillouin-orthorhombic-mp-1183085.svg
  assets/svg/brillouin-tetragonal-mp-1207297.svg
  assets/svg/brillouin-triclinic-mp-686119.svg
  assets/svg/brillouin-trigonal-mp-1183057.svg
  pymatviz/__init__.py
  pymatviz/brillouin.py
  pyproject.toml
  readme.md
  tests/files/structures/mp-10018-Ac1-cubic.json.gz
  tests/files/structures/mp-1183057-Ac3-trigonal.json.gz
  tests/files/structures/mp-1183085-Ac4Mg2-orthorhombic.json.gz
  tests/files/structures/mp-1183089-Ac4Mg2-monoclinic.json.gz
  tests/files/structures/mp-1207297-Ac2Br2O1-tetragonal.json.gz
  tests/files/structures/mp-686119-Ag13Bi14I56-triclinic.json.gz
  tests/files/structures/mp-862690-Ac4-hexagonal.json.gz
  tests/test_brillouin.py
Labels: plotly, feature
