Repository janosh/pymatviz, pull requests merged in 2024-09, with the labels that each got.

#195 Bump min supported Python to 3.10
  .github/workflows/test.yml
  .pre-commit-config.yaml
  examples/dataset_exploration/matpes/eda.py
  examples/make_assets/phonons.py
  examples/make_assets/scatter.py
  examples/make_assets/uncertainty.py
  pymatviz/bar.py
  pymatviz/io.py
  pymatviz/phonons.py
  pymatviz/powerups/both.py
  pymatviz/powerups/matplotlib.py
  pymatviz/powerups/plotly.py
  pymatviz/ptable/_process_data.py
  pymatviz/ptable/_projector.py
  pymatviz/ptable/ptable_matplotlib.py
  pymatviz/ptable/ptable_plotly.py
  pymatviz/py.typed
  pymatviz/scatter.py
  pymatviz/structure_viz.py
  pymatviz/uncertainty.py
  pymatviz/utils.py
  pymatviz/xrd.py
  pyproject.toml
  readme.md
  tests/conftest.py
  tests/powerups/test_matplotlib_powerups.py
  tests/powerups/test_plotly_powerups.py
  tests/test_io.py
  tests/test_phonons.py
  tests/test_readme.py
  tests/test_uncertainty.py
  tests/test_utils.py
Labels: breaking, pkg, ci, types

#196 ruff fixes
  .pre-commit-config.yaml
  examples/dataset_exploration/ricci_carrier_transport/convert_dtype+add_structs.py
  examples/make_assets/phonons.py
  examples/make_assets/ptable/ptable_matplotlib.py
  pymatviz/bar.py
  pymatviz/cumulative.py
  pymatviz/enums.py
  pymatviz/histogram.py
  pymatviz/io.py
  pymatviz/phonons.py
  pymatviz/powerups/both.py
  pymatviz/powerups/plotly.py
  pymatviz/ptable/_process_data.py
  pymatviz/sankey.py
  pymatviz/scatter.py
  pymatviz/sunburst.py
  pymatviz/uncertainty.py
  pymatviz/utils.py
  pymatviz/xrd.py
  pyproject.toml
  tests/powerups/test_both_powerups.py
  tests/powerups/test_matplotlib_powerups.py
  tests/powerups/test_plotly_powerups.py
  tests/ptable/test_ptable_matplotlib.py
  tests/ptable/test_ptable_plotly.py
  tests/ptable/test_ptable_projector.py
  tests/test_bar.py
  tests/test_io.py
  tests/test_phonons.py
  tests/test_process_data.py
  tests/test_relevance.py
  tests/test_sankey.py
  tests/test_scatter.py
  tests/test_sunburst.py
  tests/test_utils.py
  tests/test_xrd.py
Labels: housekeeping, types

#198 Add `IS_IPYTHON` global
  .pre-commit-config.yaml
  assets/histogram-ecdf.svg
  examples/make_assets/histogram.py
  pymatviz/__init__.py
  pymatviz/structure_viz.py
  readme.md
  tests/__init__.py
  tests/test_pkg.py
  tests/test_structure_viz.py
Labels: enhancement

#203 `element_pair_rdfs` plots radial distribution functions (RDFs) for element pairs in a structure
  assets/element-pair-rdfs-Na8Nb8O24.svg
  assets/element-pair-rdfs-Si16O32.svg
  examples/make_assets/rdf.py
  pymatviz/__init__.py
  pymatviz/rdf.py
  pymatviz/templates.py
  readme.md
  tests/test_rdf.py
Labels: enhancement, plotly

#204 Fix RDF SVG asset paths in readme
  assets/element-pair-rdfs-Na8Nb8O24.svg
  assets/element-pair-rdfs-Si16O32.svg
  examples/make_assets/rdf.py
  pymatviz/__init__.py
  pymatviz/rdf.py
  pymatviz/templates.py
  readme.md
  tests/test_rdf.py
Labels: docs

#202 Exclude `tests` from source distribution, and drop python2 tag for wheel
  pyproject.toml
  readme.md
Labels: pkg

#205 Add kwarg `use_tooltips: bool = True` to `df_to_html` (prev `df_to_html_table`)
  pymatviz/__init__.py
  pymatviz/io.py
  pymatviz/rdf.py
  site/package.json
  tests/test_io.py
  tests/test_rdf.py
Labels: breaking, api, io

#206 Support `list`/`dict` of structures in `element_pair_rdfs`
  assets/element-pair-rdfs-crystal-vs-amorphous.svg
  examples/make_assets/rdf.py
  pymatviz/rdf.py
  readme.md
  tests/test_rdf.py
Labels: enhancement, rdf

#211 Fix `calculate_rdf` not accounting for periodic boundaries
  assets/element-pair-rdfs-Na8Nb8O24.svg
  assets/element-pair-rdfs-Si16O32.svg
  assets/element-pair-rdfs-crystal-vs-amorphous.svg
  pymatviz/io.py
  pymatviz/rdf.py
  pymatviz/structure_viz.py
  tests/test_rdf.py
Labels: fix, rdf

#212 Fix `xrd_pattern` not allowing `annotate_peaks=0` to disable peak annotation
  .pre-commit-config.yaml
  pymatviz/rdf.py
  pymatviz/utils.py
  pymatviz/xrd.py
  tests/test_rdf.py
  tests/test_xrd.py
Labels: fix, xrd, rdf

#213 Add `structure_2d_plotly` to `pymatviz/structure_viz.py`
  assets/matbench-phonons-structures-2d-plotly.svg
  examples/make_assets/structure_viz.py
  pymatviz/__init__.py
  pymatviz/structure_viz.py
  readme.md
  tests/test_structure_viz.py
Labels: enhancement, plotly, structure

#207 Clean up var names in unit tests, avoid MP API access in GitHub workflow
  .github/workflows/test.yml
  examples/make_assets/structure_viz.py
  tests/conftest.py
  tests/files/structures/mp-12712.json.gz
  tests/files/structures/mp-19017.json.gz
  tests/test_bar.py
  tests/test_io.py
  tests/test_scatter.py
  tests/test_structure_viz.py
  tests/test_uncertainty.py
  tests/test_xrd.py
Labels: testing, linting

#214 Add `structure_3d_plotly`
  assets/matbench-phonons-structures-2d-plotly.svg
  assets/matbench-phonons-structures-3d-plotly.svg
  examples/make_assets/structure_viz.py
  pymatviz/__init__.py
  pymatviz/structure_viz/__init__.py
  pymatviz/structure_viz/helpers.py
  pymatviz/structure_viz/mpl.py
  pymatviz/structure_viz/plotly.py
  readme.md
  tests/structure_viz/test_helpers.py
  tests/structure_viz/test_mpl.py
  tests/structure_viz/test_plotly.py
Labels: enhancement, plotly, structure

#217 pin kaleido==0.2.1
  pyproject.toml
Labels: pkg, deps
