Repository janosh/pymatviz, pull requests merged in 2024-08, with the labels that each got.

#191 Re-export all submodules/subpackages from `pymatviz.__init__.py`
  pymatviz/__init__.py
  tests/test_init.py
  tests/test_pkg.py
Labels: enhancement, ux, pkg

#192 `bin_df_cols` leave input df unchanged
  pymatviz/process_data.py
  pymatviz/ptable/ptable_plotly.py
  pymatviz/utils.py
  pyproject.toml
  tests/test_process_data.py
  tests/test_utils.py
Labels: enhancement, ux

#193 `density_scatter_plotly` add kwarg `facet_col: str | None = None`
  examples/make_assets/scatter.py
  pymatviz/enums.py
  pymatviz/io.py
  pymatviz/powerups/both.py
  pymatviz/scatter.py
  pymatviz/utils.py
  tests/conftest.py
  tests/powerups/test_both_powerups.py
  tests/ptable/test_ptable_plotly.py
  tests/test_histogram.py
  tests/test_pkg.py
  tests/test_scatter.py
  tests/test_utils.py
Labels: enhancement, plotly, scatter

#187 Fix `svgo` workflow for ptable scatter plots
  .github/workflows/svgo.yml
  assets/ptable-heatmap-plotly-more-hover-data.svg
Labels: fix, ci

#194 Self-import refactor
  .pre-commit-config.yaml
  assets/density-scatter-plotly.svg
  examples/dataset_exploration/boltztrap_mp/explore_boltztrap_mp.py
  examples/dataset_exploration/camd_2022/explore_camd_2022.py
  examples/dataset_exploration/matbench/dielectric/explore_dielectric.py
  examples/dataset_exploration/matbench/expt_gap/explore_expt_gap.py
  examples/dataset_exploration/matbench/jdft2d/explore_jdft2d.py
  examples/dataset_exploration/matbench/log_g+kvrh/explore_log_g+krvh.py
  examples/dataset_exploration/matbench/mp_e_form/explore_mp_e_form.py
  examples/dataset_exploration/matbench/mp_gap/explore_mp_gap.py
  examples/dataset_exploration/matbench/perovskites/explore_perovskites.py
  examples/dataset_exploration/matbench/phonons/explore_phonons.py
  examples/dataset_exploration/matbench/steels/explore_steels.py
  examples/dataset_exploration/matpes/eda.py
  examples/dataset_exploration/ricci_carrier_transport/explore_carrier_transport.py
  examples/dataset_exploration/wbm/explore_wbm.py
  examples/diatomics/plot.py
  examples/make_assets/correlation.py
  examples/make_assets/histogram.py
  examples/make_assets/phonons.py
  examples/make_assets/powerups.py
  examples/make_assets/ptable/ptable_matplotlib.py
  examples/make_assets/ptable/ptable_plotly.py
  examples/make_assets/relevance.py
  examples/make_assets/sankey.py
  examples/make_assets/scatter.py
  examples/make_assets/structure_viz.py
  examples/make_assets/symmetry.py
  examples/make_assets/uncertainty.py
  examples/make_assets/xrd.py
  examples/matbench_dielectric_eda.ipynb
  examples/matbench_perovskites_eda.ipynb
  examples/mlff_phonons.ipynb
  examples/mprester_ptable.ipynb
  pymatviz/__init__.py
  pymatviz/histogram.py
  pymatviz/io.py
  pymatviz/powerups/both.py
  pymatviz/scatter.py
  pymatviz/sunburst.py
  pymatviz/uncertainty.py
  tests/conftest.py
  tests/powerups/test_both_powerups.py
  tests/powerups/test_matplotlib_powerups.py
  tests/ptable/test_ptable_matplotlib.py
  tests/ptable/test_ptable_plotly.py
  tests/test_io.py
  tests/test_phonons.py
  tests/test_process_data.py
  tests/test_sankey.py
  tests/test_structure_viz.py
  tests/test_templates.py
  tests/test_utils.py
  tests/test_xrd.py
Labels: housekeeping, pkg
